"""Add Status Column

Revision ID: f0187df84600
Revises: 77a4fe9a90ed
Create Date: 2025-05-04 19:39:19.322434

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0187df84600"
down_revision: Union[str, None] = "77a4fe9a90ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("emails", sa.Column("status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("emails", "status")
    # ### end Alembic commands ###
